### ISSUE TITLE
Ability to set headers

### ISSUE THREAD

**Issue by kristian-puccio** [bahmutov/start-server-and-test#113]
If this is a new feature request, please describe it below

Hi I'm just trying to get this to work with apollo-server [https://www.apollographql.com/docs/apollo-server/api/apollo-server.html].
If you send a HEAD request you get a 405 - Method not allowed.
If you send a GET request with no headers you get a 400 - Bad request.

BUT if you add the header 'Accept': 'text/html' it works.

It's a bit of a weird situation, I think it's because apollo-server does a check to see wether to show the playground or use the api.

I'm not sure what the best solution would be maybe allowing custom headers to be passed to wait-on but in my situation I'm waiting on 2 servers to wake up, though the extra headers on the server that works fine with the HEAD request doesn't hurt.

Thanks and great work on the project by the way.

Cheers,
Kristian

**Comment by dz14** [comment]
@kristian-puccio How did you add the extra headers on Apollo Server to get it working? Thanks

**Comment by kristian-puccio** [comment]
@dz14 Yeah I'm not sure it just works now.

**Comment by dz14** [comment]
@kristian-puccio Weird, I just tried it today but it couldn't detect that Apollo Server started and stays like that with the tests never started. Please advise if you did something else in your case to get it working.

**Comment by dz14** [comment]
managed to get it to work. I just had to pass in a valid GET request for Apollo Server. Just a plain http://localhost:4000 would be rejected by Apollo Server.

**Comment by darrellwarde** [comment]
Just wanted to expand on this in case anyone else comes up against any problems. Apollo Server will respond with a 405 error to the default HEAD requests that this start-server-and-test uses, and if you use a GET request you need to pass some valid GraphQL into the `query` URL parameter. Following the first example in the project README, the following script command using a basic schema introspection query will work for a default Apollo Server instance:

```
"start-server-and-test start-server 'http-get://localhost:4000/graphql?query={ __schema { queryType { name } } }' test"
```

**Comment by zkwsk** [comment]
Thank you guys!

To the maintainers, it took me quite a while to find this info. Is there any chance of adding this to the readme, or maybe providing a flag to use when testing an apollo server that will pass in a query automatically?

**Comment by bahmutov** [comment]
Sure we would be happy to clarify this. What would you like to change in the readme? Do you want to submit a pull request with proposed changes?

**Comment by zkwsk** [comment]
Sure. I just added a PR to update the readme.
