### ISSUE TITLE
The ps-tree package may be unsafe now. Better find an alternative.

### ISSUE THREAD

**Issue by sodatea** [bahmutov/start-server-and-test#128]
See:
https://github.com/indexzero/ps-tree/issues/33
https://github.com/dominictarr/event-stream/issues/116

**Comment by indexzero** [comment]
FYI `ps-tree@1.1.1` locked to `event-stream@3.3.4` (which if I read this thread correctly pre-dates the questionable changes). 

Thanks to folks for bringing it to my attention: https://github.com/indexzero/ps-tree/pull/34

**Comment by dervism** [comment]
It's also possible to add the following to the dependencies to lock the affected package to a safe version: 

```
"dependencies": {
     "event-stream": "=3.3.4"
  }

```

**Comment by bahmutov** [comment]
so right now this package uses `ps-tree@1.2.0` which uses `event-stream@3.3.4` which I believe is safe
```
$ npm ls event-stream
start-server-and-test@0.0.0-development /Users/gleb/git/start-server-and-test
└─┬ ps-tree@1.2.0
  └── event-stream@3.3.4
```

If any other changes is necessary, please let me know
