### ISSUE TITLE
Error: spawn ps ENOENT

### ISSUE THREAD

**Issue by lorensr** [bahmutov/start-server-and-test#132]
## Is this a bug report or a feature request?

Bug

- version
```
npm -v start-server-and-test
5.6.0
```
- platform
linux: `alpine-node`
- expected behavior
Exits with code 0 at end of test
- actual behavior
After tests complete, I get `Error: spawn ps ENOENT`, and exits with code 1
```
    All specs passed!                           00:27       15       15        -        -        -  

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! packlist@0.1.0 test:e2e: `start-server-and-test start:qa http-get://0.0.0.0:8080 cy:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the packlist@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-01T05_09_26_197Z-debug.log
Exited with code 1
```

It looks like this started when I added `env` to the beginning of `start:web`?

```
    "start:web": "env APP_ENV=dev webpack-dev-server --inline --hot --host 0.0.0.0",
    "test:e2e": "start-server-and-test start:web http-get://0.0.0.0:8080 cy:run",
    "cy:run": "cypress run",
```

I need to keep `env`. Any suggestions on what I should try? Thanks!

**Comment by lorensr** [comment]
This `catch()` function is not being called:

```js
startAndTest({ start, url, test }).catch((e) => {
  console.error('here', e);
  process.exit(1);
});
```

**Comment by Winify** [comment]
Having the same problem.

Trying to run an E2E test from a **docker** container while running the application on localhost in the same container.

```
        "protractor": "protractor protractor.conf.js",
        "docker-e2e:test": "server-test start 3000 protractor"
```

Running the script outside the docker container yields no problem,
while executing from the inside produces: 
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

Additionally inside the docker container the started server does not stop after the test run.

Any suggestions?

**Comment by Winify** [comment]
> This `catch()` function is not being called:
> 
> ```js
> startAndTest({ start, url, test }).catch((e) => {
>   console.error('here', e);
>   process.exit(1);
> });
> ```

Had the same problem, I switched the docker base to` node:10.11.0-alpine` and the start-server-and-test package version from `1.7.11` to `1.7.1` and somehow these changes did the trick for me.

**Comment by hapit** [comment]
I had the same problem in a different project. The reason is that alpine doesn't have the 'ps' command istalled by default.

I fixed it by installing it in my container:
`sudo apt-get update && sudo apt-get -y install procps`

**Comment by lorensr** [comment]
Thank you! That fixed

**Comment by JeremyCraigMartinez** [comment]
If you were using alpine, wouldn't this `apt-get` command have to be `apk add`?

**Comment by MikeMcC399** [comment]
Since this issue was linked by #504, I re-tested it with a current supported `node:alpine` image, and confirm that the issue no longer occurs, as already stated above.

## Steps to verify

```shell
git clone https://github.com/bahmutov/start-server-and-test
cd start-server-and-test
npm ci

docker run --rm -v .:/app -w /app --entrypoint sh node:lts-alpine -c "npm test"
```

All tests succeed. 👍🏻
