### ISSUE TITLE
start-server-and-test > wait-on > joi > hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

### ISSUE THREAD

**Issue by basslagter** [bahmutov/start-server-and-test#143]
When installing (using Yarn) the following warning is shown:

start-server-and-test > wait-on > joi > hoek@5.0.4: This version is no longer maintained. Please upgrade to the latest version.

**Comment by basslagter** [comment]
Bump! 
Seems due to an old version of the wait-on dependency.

**Comment by bahmutov** [comment]
hmm, weird, TravisCI stopped doing PR status checks, but I have merged the PR that upgrades `wait-on`, watch for release
