### ISSUE TITLE
Command timeout

### ISSUE THREAD

**Issue by pvtri96** [bahmutov/start-server-and-test#148]
Can we have another argument/parameter to configure the timeout of the command? 
For example: After waiting 2 minutes without any response from the endpoint. The process will exit with code 1.

Thank for your great work with this project.
Cheer.

**Comment by charlex** [comment]
This feels like a helpful feature to me as well. Would keep my CI jobs from creeping up to their max timeouts, thereby saving time!

**Comment by Nightbr** [comment]
+1 for a timeout parameter, a must have for CI :)

**Comment by pvtri96** [comment]
[1.9.0](https://github.com/bahmutov/start-server-and-test/releases/tag/v1.9.0) has already shipped with a timeout of 5 minutes. For CI environment, I think it would suffice for me.
