### ISSUE TITLE
Error: server closed unexpectedly

### ISSUE THREAD

**Issue by BrunoAFK** [bahmutov/start-server-and-test#180]
I have problems with even start server etc. I was following instructions, and I can't make this thing to work. So here is more information:

## What I want to achieve
- I'm using cypress to test my html/js/css website (a basic site that is using gulp to do better optimization etc).
- I was trying several ways that are described over the internet but without success
- I want that this script works on Netlify too
- I need a server that is running on the port 5000

## What I was trying to do?

`npm run deploy
`

Build process finished fine, but then here is an error:

>  start-server-and-test start cy:run
> 
> starting server using command "npm run start"
> and when url "undefined" is responding
> running tests using command "npm run test"
> /home/bruno_afk/Dev/paveljame-site/node_modules/lazy-ass/index.js:117
>       throw err;
>       ^
> 
> Error: missing url to wait on null
>     at lazyAssLogic (/home/bruno_afk/Dev/paveljame-site/node_modules/lazy-ass/index.js:110:14)
>     at lazyAss (/home/bruno_afk/Dev/paveljame-site/node_modules/lazy-ass/index.js:115:28)
>     at startAndTest (/home/bruno_afk/Dev/paveljame-site/node_modules/start-server-and-test/src/index.js:24:3)
>     at Object.<anonymous> (/home/bruno_afk/Dev/paveljame-site/node_modules/start-server-and-test/src/bin/start.js:13:1)
>     at Module._compile (internal/modules/cjs/loader.js:776:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
> npm ERR! Test failed.  See above for more details.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! paveljame@0.6.0 predeploy: `CI=1 npm i cypress; npm run develop; npm test`
> npm ERR! Exit status 1
> 

## My npm scripts

```
"scripts": {
        "gulp": "node_modules/.bin/gulp",
        "start-server-and-test": "node_modules/.bin/start-server-and-test",
        "start": "start-test -p 5000",
        "test": "start-server-and-test start cy:run",
        "dev": " gulp publish",
        "develop": "gulp build",
        "build": "gulp publish",
        "predeploy": "CI=1 npm i cypress; npm run develop; npm test",
        "deploy": "npm run build",
        "cy:run": "cypress run",
        "cy:open": "cypress open"
    },
```

- node version: 10.16.0
- npm version: 6.9.0
- package version: 1.9.1
- PopOS 19.04 (linux)

**Comment by bahmutov** [comment]
right, the url to wait on is undefined - because the utility does not know which port or url to wait for.  In your scripts I don't see how you start the server - `npm run gulp`? So just start the server with that command and then pass port number to the "test" like this

```json
{
  "scripts": {
    "start": "gulp",
    "test": "star-test 5000 cy:run",
    "cy:run": "cypress run"
  }
}
```

Note that you don't need to say `start` there in "test: start-test start 5000 cy:run" because you are using the default "start" script to run the server
