### ISSUE TITLE
Launched processes not closed after tests have ended

### ISSUE THREAD

**Issue by tkivela** [bahmutov/start-server-and-test#2]
## Is this a bug report or a feature request?
Bug report
- version
 1.0.1
- platform
 Debian 9.3 (Linux)
- expected behavior
 After running tests the processes which it started should have been shut down
- actual behavior
 Some node processes seem still be running (in the example repo stated below there is still parcel bundler running which serves the pages after the tests have been completed).

Repository which can be used to reproduce the bug: https://github.com/tkivela/hyperapptemplate_ts
Start e2e tests by running "npm run e2etest" (or "yarn e2etest")

**Comment by bahmutov** [comment]
There was a pull request that I think solves this problem (children processes created by the server), can you try https://github.com/bahmutov/start-server-and-test/releases/tag/v1.1.0 ?

**Comment by coun7zero** [comment]
@bahmutov it works, thanks! :)

**Comment by bahmutov** [comment]
perfect, closing the issue
