### ISSUE TITLE
Feature Request: Shortcuts

### ISSUE THREAD

**Issue by allenhwkim** [bahmutov/start-server-and-test#23]
Thanks for this wonderful module first. This is very useful for my acceptance test.

For lazy developer like me, can you make the CLI shorter than the existing one?

* `server-test` as the shortcut of `start-server-and-test`
* `8080` as shortcut of `http://localhost:8080` or `https://localhost:8080`

For example,
* `server-test 8080`
* `server-test start-server 8080`
* `server-test start 8080 my-test`

@bahmutov if you are ok with it, I can make a PR.

**Comment by bahmutov** [comment]
Love it! How would it know if the port number is a short cut to `http://locahost:<port>` or `https://localhost:<port>`? I guess usually localhost means `http` ...

**Comment by allenhwkim** [comment]
Thanks for the quick response.
On the second thought `https` test will it be difficult because every browser treat unsigned http differently.
