### ISSUE TITLE
start server once and run two tests with different runner

### ISSUE THREAD

**Issue by mike-4040** [bahmutov/start-server-and-test#304]
Not sure if this a FR or just documentation.
We have some functional tests in mocha, some in jest, and I have to start the test server twice.

Can't figure out how I can start the server once and run two tests with different runners.

**Comment by bahmutov** [comment]
If you want to start the server, wait for it to respond, and then run multiple test commands (and stop the server after they finish), you should be able to use `&&` to separate the test commands:

```json
{
  "scripts": {
    "start": "npm start",
    "test:unit": "mocha test.js",
    "test:e2e": "mocha e2e.js",
    "ci": "start-test 9000 'npm run test:unit && npm run test:e2e'"
  }
}
```

The above script `ci` after the `localhost:9000` responds executes the `npm run test:unit` command. Then when it finishes it runs `npm run test:e2e`. If the first or second command fails, the `ci` script fails. Of course, your mileage on Windows might vary.
