### ISSUE TITLE
work with vite server

### ISSUE THREAD

**Issue by shanoysinc** [bahmutov/start-server-and-test#312]
I am using a react app with vite  and when I use start-server-and-test the server starts but cy:run doesn't run 

script -  start-server-and-test dev http://localhost:3000 cy:open

my server starts on 3000 but I get an error after

Error: Timed out waiting for: http://localhost:3000

**Comment by bahmutov** [comment]
Can you create a public repo with the problem?

**Comment by shanoysinc** [comment]
https://github.com/shanoysinc/Path-Visualizer

**Comment by oliverturner** [comment]
A minimal repro can be seen here: 
https://github.com/oliverturner/start-server-vite-minimal-repro
