### ISSUE TITLE
Perpetual ECONNREFUSED when running on bare-bones nextjs app

### ISSUE THREAD

**Issue by thepuzzlemaster** [bahmutov/start-server-and-test#325]
## bug report

- version 1.14.0
- platform OSX

Repro steps
I ran into an issue on my fairly large nextjs app when moving from a custom server which ran using https to the `next start` server running on http. I was able to make a minimal repro [here](https://github.com/thepuzzlemaster/playwright-defect-repro). (kindly ignore the repo name. That was initially created for a different issue)

- `yarn install`
- `yarn test:integration`

running `curl http://localhost:3333` returns the html string
I'm using `http-get` on account of the webpack dev server.

- expected behavior
  - start-server-and-test recognizes the running server and kicks off the test suite
- actual behavior
  - Permanent loop of ECONNREFUSED errors until timeout limit is reached

I've tried tcp:3333 syntax, with the same result. I'm really not sure why it can't reach the server address.

**Comment by thepuzzlemaster** [comment]
Well, interestingly enough, it works fine using `127.0.0.1:3333`, rather than `localhost:3333`

I also see the same behavior using just `wait-on`, so this seems to be related to that dependency, not this module.

**Comment by nephix** [comment]
Ran into the same problem
Related issue in `wait-on`: https://github.com/jeffbski/wait-on/issues/109
