### ISSUE TITLE
Cannot customize WAIT_ON_TIMEOUT 

### ISSUE THREAD

**Issue by muratkeremozcan** [bahmutov/start-server-and-test#329]
- version:    1.14.0
- platform:    any 
- expected behavior:   should be able to cutomize timeout
- actual behavior:  cannot customize timeout

Easy repro

```bash
git clone https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress.git
cd react-hooks-in-action  
yarn
git checkout repro-start-server-issue
yarn cy:run-e2e
```

WAIT_ON_TIMEOUT is set to 1 ms, but things still work. 

[Here is the CI version](https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress/pull/62/files)

**Comment by pakhilov** [comment]
<img width="1144" alt="Screen Shot 2022-03-09 at 9 16 39 AM" src="https://user-images.githubusercontent.com/10390058/157549335-9d337b8b-4b36-48f3-aa0e-16713446be03.png">

**Comment by muratkeremozcan** [comment]
Setting the timout to 1 ms will somehow work locally, but for sure fails the CI. This is okay behavior.

https://github.com/muratkeremozcan/react-hooks-in-action-with-cypress/runs/5487906796?check_suite_focus=true
