### ISSUE TITLE
Error: spawn ps ENOENT 

### ISSUE THREAD

**Issue by joelgrimberg** [bahmutov/start-server-and-test#330]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
definitely a bug report ;)

If this is a bug report, please provide as much info as possible

- version

1.13 / 1.14 running on cypress/included:9.5.2 and cypress/included:9.5.3

- platform

Linux

- expected behavior

start-server-and-tests quits webserver after tests

- actual behavior

`node:events:498
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}`

I have setup a demo repo here where you can see the setup:
https://gitlab.com/joelgrimberg/cypress-failing-with-953

If I run it within a cypress/included:9.5.1 container, all is fine:
https://gitlab.com/joelgrimberg/cypress-failing-with-953/-/jobs/2281876715

if I un it witin a cypress/included:9.5.2 container, the start-server-and-test fails:
https://gitlab.com/joelgrimberg/cypress-failing-with-953/-/jobs/2281897953

if I un it witin a cypress/included:9.5.2 container, the start-server-and-test fails:
https://gitlab.com/joelgrimberg/cypress-failing-with-953/-/jobs/2281921034

trying to debug the issue, already tried installing ps-tree and execa globally but that did not work out.

**Comment by blurbyte** [comment]
Got exactly same problem. From my (limited) tests on CircleCI:
- ✅ everything was working fine on: **cypress/base:16.13.0** docker image and **cypress v9.5.1** npm dependency
- 🚫 error started to appear after bumping dependencies to: **cypress/base:16.14.2** and **cypress v9.5.3**
- 🚫 error also appeared on: **cypress/base:16.13.0** and *cypress v9.5.3**

**Comment by GreoGi** [comment]
I also got same problem. From my tests on GitlabCI:
- ✅ everything was working fine on: cypress/base:16.13.0 docker image and cypress v9.5.4 npm dependency
- 🚫 error appeared on: cypress/base:16.14.2 and cypress v9.5.2
- 🚫 error appeared on: cypress/base:16.14.2 and cypress v9.5.4

**Comment by joelgrimberg** [comment]
I just tested with Cypress v9.6.0 and all is well now. 🥳 so I will close this issue.

**Comment by ekeih** [comment]
Hm, interesting. I am still seeing the same issue with `cypress/base:16.14.2` and `v9.6.0`.
