### ISSUE TITLE
Node 17 support

### ISSUE THREAD

**Issue by rtrembecky** [bahmutov/start-server-and-test#333]
## Bug report

Hi, as mentioned in #328 by several people, it seems the package doesn't support node 17+ or at least is unable to execute a command after the server is up and ready. I created a new issue in case it is a different topic than #328 (probably is).

- version: 1.14.0 (latest)
- platform: macOS Monterey 12.2.1
- expected behavior: running `start-server-and-test start 8000 cy:open` should start the app server and open Cypress
- actual behavior: running this ^ starts the server but doesn't open Cypress, hence it eventually times out

**Comment by itsyoboieltr** [comment]
bump

**Comment by rodoabad** [comment]
It's been awhile since we saw an update for this repository so it might take awhile. :-(

**Comment by gndelia** [comment]
I'm seeing the same issue with node 16, but I'm not with node 14. but instead of Cypress, I see it with serverless-offline

**Comment by rodoabad** [comment]
Node 16 should work. 17+ does not.

**Comment by CamilleDrapier** [comment]
This might be related to this issue (of the underlying `wait-on` lib), and the proposed solution/fallback (replace `localhost` by local IP) might work for people seeing this problem here: https://github.com/jeffbski/wait-on/issues/109#issue-1071849300

**Comment by rodoabad** [comment]
Giving an update on our end here. We ended up using `concurrently` and `wait-on` in order for us to move to Node 18.

**Comment by rodoabad** [comment]
> This might be related to this issue (of the underlying `wait-on` lib), and the proposed solution/fallback (replace `localhost` by local IP) might work for people seeing this problem here: [jeffbski/wait-on#109 (comment)](https://github.com/jeffbski/wait-on/issues/109#issue-1071849300)

What we did was actually the opposite (people can either do it one way or another).

We had a server that was starting at `0.0.0.0:8080` and `wait-on` couldn't wait for it since `wait-on` was waiting for `localhost:8080`. What we did instead is, change `0.0.0.0:8080` to `localhost:8080` and it worked on us. We didn't have to change our npm script to include `http://localhost:8080` for `start-server-and-start` it still stay at `8080` (shorthand).

**Comment by spectronp** [comment]
> This might be related to this issue (of the underlying `wait-on` lib), and the proposed solution/fallback (replace `localhost` by local IP) might work for people seeing this problem here: [jeffbski/wait-on#109 (comment)](https://github.com/jeffbski/wait-on/issues/109#issue-1071849300)

It worked for me with 127.0.0.1

**Comment by actuallymentor** [comment]
Can confirm it does not work for `18 lts` either.

**Comment by nbouvrette** [comment]
@bahmutov is there any plan to fix this issues? Many tools are now using Node 18 as the default version since we are only [6 months away](https://endoflife.date/nodejs) from having no support on Node 16.

**Comment by bahmutov** [comment]
Yes I will look into this

**Comment by bahmutov** [comment]
Can someone provide a reproducible example? I have tested this tool using Node v18 in https://github.com/bahmutov/start-server-and-test/pull/354 and don't see any problems.

**Comment by cbookg** [comment]
In my project only Mac users have issues, not Linux users.

**Comment by nbouvrette** [comment]
@bahmutov I just tested with version 2 and I got the issue happening again. I suspect there is another issue to fix.

 It's only happening on this script:

```json
    "e2e-build-headless-base-path": "cross-env CYPRESS_isProd=true BASE_PATH=/some-path CYPRESS_basePath=/some-path start-server-and-test start-example-build http://localhost:3000/some-path cypress-headless",
```
This one seems to work fine:

```json
    "e2e-build-headless": "cross-env CYPRESS_isProd=true start-server-and-test start-example-build http://localhost:3000 cypress-headless",
```

Feel free to try to reproduce cloning this repo: https://github.com/Avansai/next-multilingual

Can run `npm run test` which will run all the different commands, and if you replace `127.0.0.1` when using Node 18, it will freeze at the 3rd command.

**Comment by MikeMcC399** [comment]
@nbouvrette 

Could you say which OS you are testing on? `localhost` can work differently depending on this. I didn't find any workflows on https://github.com/Avansai/next-multilingual (.github/workflows) to give me a hint.

**Comment by nbouvrette** [comment]
I'm on macOS 13.2.1

Regarding `next-multilingual` here would be step-by-step reproductions:

1) Clone https://github.com/Avansai/next-multilingual
2) run `npm run install`
3) run `npm run build`
4) Open `package.json` and make sure that all the `127.0.0.1` are replaced by `localhost`
5) run `npm run test`

If you check the script for `npm run test` you will see that there are 4 different subscripts being run with different `start-server-and-test` steps. The 3rd step will hang, and when I press `ctrl-c` it sort of resumes but go back into the same stuck step.

**Comment by bahmutov** [comment]
Could you please open a new issue and include debugging verbose logs?Sent from my iPhoneOn Feb 27, 2023, at 22:33, Nicolas Bouvrette ***@***.***> wrote:﻿
I'm on macOS 13.2.1
Regarding next-multilingual here would be step-by-step reproductions:

Clone https://github.com/Avansai/next-multilingual
run npm run install
run npm run build
Open package.json and make sure that all the 127.0.0.1 are replaced by localhost
run npm run test

If you check the script for npm run test you will see that there are 4 different subscripts being run with different start-server-and-test steps. The 3rd step will hang, and when I press ctrl-c it sort of resumes but go back into the same stuck step.

**Comment by nbouvrette** [comment]
Sure. How do I turn on verbose logs?

**Comment by bahmutov** [comment]
Check out the debugging section of the readme. Just need to set DEBUG env variable when running with the name of the module Sent from my iPhoneOn Feb 27, 2023, at 22:59, Nicolas Bouvrette ***@***.***> wrote:﻿
Sure. How do I turn on verbose logs?

**Comment by MikeMcC399** [comment]
@nbouvrette 
> I'm on macOS 13.2.1

I was hoping to be able to try this out, however on https://github.com/actions/runner-images `macos-latest` is equivalent to [macos-12](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md) so your version is not yet available. I'll be interested if you open a new issue and provide debug logs anyway.
