### ISSUE TITLE
Startup message "is responding with HTTP status code NaN"

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/start-server-and-test#349]
# Bug report

## Configuration

[start-server-and-test](https://github.com/bahmutov/start-server-and-test) 1.15.3
Ubuntu 22.04 and Node.js 18.13.0
Windows 11 and Node.js 18.13.0

## Problem description

[start-server-and-test](https://github.com/bahmutov/start-server-and-test)

When running a script defined as:

```text
start-server-and-test start-server http://localhost:8000 cypress:run
```

the following message is output:

```text
1: starting server using command "npm run start-server"
and when url "[ 'http://localhost:8000' ]" is responding with HTTP status code NaN
running tests using command "npm run cypress:run"
```

This is a regression from version 1.14.0 where the message was
" ... is responding with HTTP status code 200"

i.e. `200` has been replaced by `NaN`.

## Expected behavior

[start-server-and-test v1.15.0](https://github.com/bahmutov/start-server-and-test/releases/tag/v1.15.0) introduced the `--expect` parameter, however there is no statement in [README: expected](https://github.com/bahmutov/start-server-and-test#expected) to say that this parameter is required, so if the default HTTP code is still `200` then the startup message should also list `200` and not `NaN` (Not a Number) if no `--expect` parameter is supplied.

**Comment by applesaucesome** [comment]
+1

**Comment by mihailgaberov** [comment]
+1

**Comment by MikeMcC399** [comment]
@bahmutov 

Could you take a look at this cosmetic regression please?

**Comment by MikeMcC399** [comment]
@bahmutov 

Thank you! I've updated to this version and confirm that it is working fine again now.

```text
1: starting server using command "npm run start-server"
and when url "[ 'http://localhost:8000' ]" is responding with HTTP status code 200
```
