### ISSUE TITLE
How to disable insecure with multiple dev environments? Why is it not an argument?

### ISSUE THREAD

**Issue by VividLemon** [bahmutov/start-server-and-test#361]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?

If this is a bug report, please provide as much info as possible

- version 2.0.0
- platform windows
- expected behavior run with insecure tests
- actual behavior doesn't

So I have the following script: `"test:e2e:ci": "set START_SERVER_AND_TEST_INSECURE=1 && start-server-and-test 'pnpm run preview' https://localhost:4173/ 'cypress run --e2e'",` 

At this point, it works fine. Note that I am on windows, and powershell prefers "set". 

Following the reference module section on here https://docs.cypress.io/guides/continuous-integration/introduction#Solutions doesn't work, I assume there's some difference between the shells. (`"test": "start-server-and-test start http://localhost:3030 cy:run"`) (I've never written that syntax to set an env variable on linux, but that doesn't mean it wouldn't work, I've just never done it before, so I'm not sure if it does)

I am trying to figure out a foolproof way to make sure that the "ci" script will run in all environments. It's a mystery to me why this is using the env, and not an _argument_. So, my issue is more of a question, as imo the docs are not very clear on getting this to work. 

Any help would be appreciated, I am aware issues aren't specifically for questions.

**Comment by codeflorist** [comment]
having the same problem. would like to run tests against https on windows as well as linux.

**Comment by MikeMcC399** [comment]
@codeflorist 

Did I understand you correctly that you want to run Cypress tests on Windows and Linux? Are you running these locally or do you use one of the CI providers listed on https://docs.cypress.io/guides/continuous-integration/ci-provider-examples?

**Comment by MikeMcC399** [comment]
@VividLemon 

- You might want to consider a tool such as [cross-env](https://www.npmjs.com/package/cross-env) or one of its follow-on solutions.

- If you are going to be using a GitHub Actions workflow later on you can set environment variables independently of the runner operating system used. See the GitHub documentation [Variables](https://docs.github.com/en/actions/learn-github-actions/variables).

- If you are interested in discussing how other users have solved this issue, you can use the [Cypress Discord chat room](https://on.cypress.io/discord).
