### ISSUE TITLE
How to allow user input from CLI?

### ISSUE THREAD

**Issue by grantspilsbury** [bahmutov/start-server-and-test#380]
I am using Percy and Cypress to run visual tests on my Nextjs app.

To run a single spec I add this to the script of my package.json
eg 

```
    "scripts": {
        "test-visual:single": "start-server-and-test 'npm run dev' http://localhost:3000 'percy exec -- cypress run --spec /path/to/test.cy.ts'",
      },
```

I want the user to enter the path of the test spec (`/path/to/test.cy.ts`). What's the right way to do this?

I have tried to use $PATH

`$PATH=/path/to/test.cy.ts npm run test-visual:single`

`"test-visual:single": "start-server-and-test 'npm run dev' http://localhost:3000 'percy exec -- cypress run --spec $PATH'",`

I have also tried:
`npm run test-visual:single /path/to/test.cy.ts`

```
    "scripts": {
        "test-visual:single": "start-server-and-test 'npm run dev' http://localhost:3000 'percy exec -- cypress run --spec $1'",
      },
```

with no luck

**Comment by MikeMcC399** [comment]
@grantspilsbury 

I guess you solved this yourself!? There is an active technical user community on Discord for Cypress

[![Discord chat](https://img.shields.io/badge/chat-on%20Discord-brightgreen)](https://on.cypress.io/discord) (click on button)

if you need any help in future about Cypress "how-to" issues.

**Comment by grantspilsbury** [comment]
> @grantspilsbury
> 
> I guess you solved this yourself!? There is an active technical user community on Discord for Cypress
> 
> [![Discord chat](https://camo.githubusercontent.com/15800a9ae6e0c62d3c4862d3300f6cf3423fee1112a6bbac2a2e51469dd47649/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f636861742d6f6e253230446973636f72642d627269676874677265656e)](https://on.cypress.io/discord) (click on button)
> 
> if you need any help in future about Cypress "how-to" issues.

Thanks Mike. I figured it wasn't really a start-server-and-test issue so I closed it
