### ISSUE TITLE
Environment variables in npm script does not work

### ISSUE THREAD

**Issue by magnusarinell** [bahmutov/start-server-and-test#57]
## Is this a bug report or a feature request?
Bug report

- version
1.4.1
- platform
Linux RHEL 7.4
- expected behavior
When using
"e2e": "env PORT=8010 start-server-and-test develop $PORT cypress:run"
I expect start-server-and-test to listen to url http://localhost:8010.
- actual behavior
starting server using command "npm run start"
and when url "undefined" is responding
running tests using command "test"
...
      throw err;
      ^

Error: missing url to wait on null
   ...
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
npm ERR! Exit status 1

**Comment by bmkrocks1** [comment]
I get the same error in my angular-cli project when using:
"ci": "start-server-and-test http-get://localhost:4200 cy:run"

**Comment by SaidTayebi** [comment]
Hello, I get the same error as well. Don't know how to pass env variables

**Comment by andrewholsted** [comment]
I've seen this same behavior. Any update?

**Comment by bahmutov** [comment]
I don't understand how it is supposed to work - you are using the environment variable `PORT` immediately to form the command. Does this work for you?
```
env PORT=8010 echo $PORT
```

No, right, it only prints an empty line. I would suggest having a command like

```
"e2e": "env PORT=8010 start-server-and-test develop 8010 cypress:run"
```

**Comment by magnusarinell** [comment]
My bug report is a year and a half old. I'm not using this anymore so I can't comment.

**Comment by bahmutov** [comment]
Yeah, I just reacted to new comment by @andrewholsted - but for now I will close this issue
