### ISSUE TITLE
need compatibility with cross-env package

### ISSUE THREAD

**Issue by tanekim77** [bahmutov/start-server-and-test#71]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
Bug
If this is a bug report, please provide as much info as possible

- version
1.5
- platform
mac
- expected behavior
no error after exist
- actual behavior
error after test finishes and exits.

-Detail:
I am using Jest library as testing package.
If I use cross-env to define environment variables for both test and start-server, then it will throw errors when the Jest test exists.
My current configuration:
    "test": "cross-env NODE_ENV=test  jest --forceExist",
    "test-server": "cross-env NODE_ENV=test  ts-node src/index.ts",
    "ci": "start-server-and-test test-server http://localhost:4000 test",

the error message when it exists the test is the following:
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typeorm@0.0.1 test-server: `cross-env NODE_ENV=test  ts-node src/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typeorm@0.0.1 test-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tanekim/.npm/_logs/2018-07-05T23_57_30_700Z-debug.log

If I remove the keywords cross-env from all lines and then run ci again, then I don't see the error message.
Also, it is a problem with mac, not windows, as I tested.

If this is a new feature request, please describe it below

**Comment by bahmutov** [comment]
hmm, that is interesting, if you can create a tiny reproducible example repo, even with dummy commands, or even better with a fix PR, I would love to fix this

**Comment by petermakowski** [comment]
I believe I run into this issue. I created an example repo here: https://github.com/petermakowski/start-server-and-test-cross-env-bug Do you think you'll have some time to look into this @bahmutov ?

**Comment by bahmutov** [comment]
Not any time soon, but could you debug this problem? Against latest code?

**Comment by bahmutov** [comment]
should be published now as version `1.7.10`

**Comment by jayphelps** [comment]
@bahmutov thanks for the quick merge and release! ❤️

**Comment by christophwolff** [comment]
Ran into the same issue with crossenv + a node server that is running. Only thing that helps is a
```
process.on('SIGTERM', () => {
  // Clean Express exit for cypress tests
})
```
In my server.js. I have no clue why.

It is a big nuxt project.
