### ISSUE TITLE
Latest release not executing tests

### ISSUE THREAD

**Issue by marko999** [bahmutov/start-server-and-test#73]
#### Running webpack-dev-server 2.11.2

Command: `start-server-and-test start-e2e http-get://localhost:4200 test-e2e`

where: 
```
"start-e2e": "webpack-dev-server --port=4200 --env.MODE=e2e"
"test-e2e": "testcafe -c 2 chrome:headless e2e/tests/nsl"
```

It gets stucked at running webpack-dev-server, doesn't execute test command(aka nothing happens, tests are not running)...

**Comment by bahmutov** [comment]
Can I see a reproducible repo? Also, did this work in previous versions of this package?

**Comment by marko999** [comment]
sorry it the client code, so I cannot post a repo, and yes it was working
for 1.4.1 which we have downgraded now in order to keep builds running

**Comment by bahmutov** [comment]
hmm, this might be a regression, but I would need a reproducible example (we do have e2e tests in this repo) to debug this. Even a simple repo might be enough to reproduce

**Comment by marko999** [comment]
Let me see if I can create a skeletin with reproducabilty

**Comment by marko999** [comment]
Resolved, it was not related to a library, we were doing some data seeding when attaching middleware to our webpack-dev-server so library was not getting response from the port...

@bahmutov  you can close this issue

**Comment by bahmutov** [comment]
Thanks for looking into this
