### ISSUE TITLE
Fail immediately if the server cannot be started 

### ISSUE THREAD

**Issue by nikolalsvk** [bahmutov/start-server-and-test#89]
Hi there @bahmutov, great work here 🤘 

I have a feature request and I'm interested in what you think.

It would be nice to have the script to fail if the server fails to start for some reason. This is my use case:

I have the `test:e2e` command set up in my `package.json` like this:

```
"start": "react-scripts start",
"cy:run": "cypress:run",
"test:e2e": "start-server-and-test start http://localhost:3000 cy:run"
```

When I run the `yarn test:e2e`, I see that the server fails to start. It has a compilation error. But the latter command (`cy:run`) starts running.

It would be nice to have it somehow fail immidiately, instead of waiting for cy:run to finish. What do you think?

**Comment by omahlama** [comment]
It's actually worse than that: we end up with a zombie process that never dies.

I think there are two fixes needed (either would solve this case, but both would help):
- Catch the exit of the server process
- Add a timeout to `waitOn`, now it uses the default timeout of `Infinity`
